Update test_analyse_in_Sonar_Cloud.yml

diff --git a/.github/workflows/test_analyse_in_Sonar_Cloud.yml b/.github/workflows/test_analyse_in_Sonar_Cloud.yml
--- a/.github/workflows/test_analyse_in_Sonar_Cloud.yml
+++ b/.github/workflows/test_analyse_in_Sonar_Cloud.yml
@@ -1,93 +1,70 @@
-name: Test and Analysis Code In Sonar Cloud
+name: Tests End-to-End
 on:
   workflow_call:
     secrets:
       ENV_PAT:
         required: true
-  push:
-    branches: 
-      - hotfix/*
-      - feature/*
-      - bugfix/*  
-
+  
   pull_request:
     types: [opened, synchronize, reopened]
-    branches:       
-      - hotfix/*
-      - feature/*
-      - bugfix/*  
+    branches:
+      - staging
 
 jobs:
-  test_code_in_sonar:
-    name: Test and Analysis Code In Sonar Cloud
-    runs-on: windows-latest
+  trigger-tests-e2e:
+    runs-on: ubuntu-latest
     steps:
-      - name: Set up JDK 17
-        uses: actions/setup-java@v3
-        with:
-          java-version: 17
-          distribution: 'zulu'
-      
-      - uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
+      - name: Trigger Workflow End-to-End
+        run: |
+            repo=${{ github.repository }}
+            file_path=$(echo "workflow_tests_e2e")
 
-      - name: Cache SonarCloud packages
-        id: cache-sonar
-        uses: actions/cache@v3        
-        with:        
-            path: ~\sonar\cache
-            key: ${{ runner.os }}-sonar
-            restore-keys: ${{ runner.os }}-sonar
-      
-      - name: Create if not Exist Cache Sonar Packages
-        if: steps.cache-sonar.outputs.cache-hit != 'true'
-        shell: powershell
+            curl -X POST \
+              -H "Authorization: token ${{ secrets.ENV_PAT }}" \
+              -H "Accept: application/vnd.github+json" \
+              -H "X-GitHub-Api-Version: 2022-11-28" \
+              https://api.github.com/repos/alexfariakof/despesas-e2e-tests/dispatches \
+              -d "{\"event_type\":\"trigger-api-e2e-tests\", \"client_payload\": {\"unit\": false, \"integration\": true, \"father_workflow_id\": \"${{ github.run_id }}\", \"path\": \"$file_path\", \"repo\": \"$repo\" }}"
+        continue-on-error: false
+
+      - name: Wait Workflow End-to-End Initialize And Update File triggered-workflow-id
+        run: sleep 15
+
+      - name: Wait for Triggered Workflow Test e2e Run
         run: |
-          New-Item -Path ~\sonar\cache -ItemType Directory    
-        
-      - name: Cache SonarCloud scanner
-        id: cache-sonar-scanner
-        uses: actions/cache@v3
-        with:
-            path: .\.sonar\scanner
-            key: ${{ runner.os }}-sonar-scanner
-            restore-keys: ${{ runner.os }}-sonar-scanner      
-          
-      
-      - name: Install SonarCloud scanner
-        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
-        shell: powershell
-        run: |
-          New-Item -Path ./.sonar/scanner -ItemType Directory
-          dotnet tool update dotnet-sonarscanner --tool-path ./.sonar/scanner
-      
-      - name: Build and analyze
+            download_url="https://raw.githubusercontent.com/${{ github.repository }}/attachments/triggered-workflow-id-${{ github.run_id }}"
+            curl -o triggered-workflow-id -L "$download_url"
+            triggered_workflow_id=$(cat triggered-workflow-id)
+            echo "Triggered Workflow ID: $triggered_workflow_id"
+
+            response=""
+            status=""
+
+            while true; do
+              response=$(curl -L \
+                -H "Accept: application/vnd.github+json" \
+                -H "Authorization: Bearer ${{ secrets.ENV_PAT }}" \
+                -H "X-GitHub-Api-Version: 2022-11-28" \
+                "https://api.github.com/repos/alexfariakof/despesas-e2e-tests/actions/runs/$triggered_workflow_id")
+
+                status=$(echo $response | jq -r '.status')
+                echo "Current status: $status"
+
+                if [ "$status" == "queued" ] || [ "$status" == "in_progress" ]; then
+                  sleep 20
+                else
+                  break
+                fi
+            done
+
+            conclusion=$(echo $response | jq -r '.conclusion')
+            echo "Conclusion: $conclusion"
+
+            if [ "$status" == "completed" ] && [ "$conclusion" == "success" ]; then
+              echo "workflow_status=${{ job.status }}" >> $GITHUB_OUTPUT
+            else
+              echo "workflow_status=failure" >> $GITHUB_OUTPUT
+              exit 1
+            fi
         env:
-            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        shell: powershell
-        run: |          
-          ./.sonar/scanner/dotnet-sonarscanner begin /k:"alexfariakof_despesas-backend-api-net-core" /o:"alexfariakof" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml" /d:sonar.exclusions="despesas-backend-api-net-core.XUnit/**,  **/MsMySqlServer.Migrations/**, **/.documents/**, *.sql, **/Program.cs, **/DataSeeders/**" /d:sonar.cs.lcov.reportPaths="**/lcov.info"
-          dotnet tool install -g dotnet-reportgenerator-globaltool
-          # Executa Build Restore com Teste e coleta o GUID gerado          
-          dotnet test ./despesas-backend-api-net-core.XUnit/XUnit.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura --collect:"XPlat Code Coverage;Format=opencover"
-            
-          # Encontra o diretório mais recente na pasta TestResults
-          $latestDir = Get-ChildItem -Directory -Path .\despesas-backend-api-net-core.XUnit\TestResults | Sort-Object LastWriteTime -Descending | Select-Object -First 1
-          $projectPath =  Join-Path -Path (Get-Location) -ChildPath ""
-          $sourceDirs = "$projectPath\Business;$projectPath\Domain;$projectPath\Repository;$projectPath\despesas-backend-api-net-core;"
-          $filefilters = "$projectPath\DataSeeders\**;$projectPath\MsMySqlServer.Migrations\**"
-
-          # Verifica se encontrou um diretório e, em caso afirmativo, obtém o nome do diretório (GUID)
-          if ($latestDir -ne $null) {
-            $guid = $latestDir.Name
-    
-            # Constrói os caminhos dinamicamente
-            $projectTestPath = Join-Path -Path (Get-Location) -ChildPath "despesas-backend-api-net-core.XUnit"
-            $coverageXmlPath = Join-Path -Path (Join-Path -Path $projectTestPath -ChildPath "TestResults") -ChildPath $guid
-            # Gera o relatório de cobertura usando o GUID capturado
-            reportgenerator -reports:$projectTestPath\coverage.cobertura.xml -targetdir:$coverageXmlPath\coveragereport -reporttypes:"Html;lcov;" -sourcedirs:$sourceDirs -filefilters:-$filefilters
-          }
-          
-          ./.sonar/scanner/dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
